### ISSUE TITLE
A default cursor after clearing measurement

### ISSUE THREAD

**Issue by d-damien** [zhenyanghua/MeasureTool-GoogleMaps-V3#10]
Hi ! In MeasureTool, the cursor goes back to 'dragging' style. In our app, the style 'default' is relevant for its precision (you see exactly where you click). Hence I suggest to add that as an option. I made a commit :

https://github.com/d-damien/MeasureTool-GoogleMaps-V3/commit/30eba3e09d988c9437d913c01340ccf9c0f786dc

Would you accept it in a PR ?

**Comment by zhenyanghua** [comment]
This is intended. When setting the map option to null, it will restore to whatever previous cursor was used. Users should be able to change cursor as part of the google maps api, it should not be part of this library. If users need to override the cursor behavior, they can do that with the events - `measure_start`, `meansure_end`.

**Comment by d-damien** [comment]
> it will restore to whatever previous cursor was used

I'm afraid it doesn't, it just sets it to default (`'grab'` [hand](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)). And behavior of `null` value is [not documented](https://developers.google.com/maps/documentation/javascript/reference#MapOptions).

> do that with the events - measure_start

I tried but could not access `addListener()` function (although I can access others like `start()`, `end()`, etc.).

I should do something like the following, right ?

``` ts
let mt = new MeasureTool(this.map, {
  showSegmentLength: false,
  unit: MeasureTool.UnitTypeId.METRIC
})

mt.addListener('measure_end', () => this.map.setOptions({ draggableCursor: 'default' }))
```

**Comment by zhenyanghua** [comment]
What version of this library are you using? Could you put up a js fiddle to help me to troubleshoot your case?

**Comment by d-damien** [comment]
Found it !
I had not seen the event api was so recent and had not updated. It works now, sorry (not for the null value though, but it's fine).
