### ISSUE TITLE
Did anyone manage to make this work with TS + jest?

### ISSUE THREAD

**Issue by plgagnon2** [zhenyanghua/MeasureTool-GoogleMaps-V3#102]
Did anyone manage to make this work with TS + jest?

**Comment by birksy89** [comment]
Not sure if this is specifically the issue you're running into - But I managed to get this to work in a TS project by adding this:

\src\react-app-env.d.ts
```
/// <reference types="react-scripts" />
declare module 'measuretool-googlemaps-v3';
```
