### ISSUE TITLE
Cannot find module 'measuretool-googlemaps-v3'

### ISSUE THREAD

**Issue by jainvizz** [zhenyanghua/MeasureTool-GoogleMaps-V3#104]
I have a project created using 'create-react-app' and I have one import in one of the file like this

`import MeasureTool from 'measuretool-googlemaps-v3';`

I am not facing any issue when I am running my project but when I am trying to run my test coverage using `npm run test ("test": "react-scripts test --env=jsdom")
`
I am getting this error **Cannot find module 'measuretool-googlemaps-v3'**

This is my jest configuration in **package.json** file

```
"jest": {
    "coverageReporters": [
      "text",
      "cobertura"
    ],
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}",
      "!/node_modules/",
      "!src/index.js",
      "!src/registerServiceWorker.js",
      "!src/setupTests.js"
    ]
  }
```

It is giving error only for this package.

**Comment by goto-bus-stop** [comment]
this project's package.json only specifies `module` and `browser` fields in package.json, not the `main` field that node.js expects. maybe jest has some configuration that you can specify to make it look for `browser` after `main`?

**Comment by zhenyanghua** [comment]
This package is intended to only work with [`browser`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#browser). It has not be tested in node.js runtime. The `main` is not provided to reflect it.
