### ISSUE TITLE
IE 11 slide map bug

### ISSUE THREAD

**Issue by d-damien** [zhenyanghua/MeasureTool-GoogleMaps-V3#11]
Hello again.

I found a bug in IE11 : when you measure some length, then try to slide the map to the east (seeing more west) ; the more you slide, the more the east side of the map disappears.

I made you a plnkr with support for IE11 : https://plnkr.co/PtjERAwbFRU5B1g2RsAY

I had to use some `Object.assign()` polyfill :
``` js
if (typeof Object.assign != 'function') {
      Object.assign = function(target) {
        'use strict';
        if (target == null) {
          throw new TypeError('Cannot convert undefined or null to object');
        }
    
        target = Object(target);
        for (var index = 1; index < arguments.length; index++) {
          var source = arguments[index];
          if (source != null) {
            for (var key in source) {
              if (Object.prototype.hasOwnProperty.call(source, key)) {
                target[key] = source[key];
              }
            }
          }
        }
        return target;
      };
}
```

 (sorry for the big copypaste of Measuretool.js, the `<script src="">` inclusion did not seem to work in plnkr)

**Comment by d-damien** [comment]
Screenshot just in case. Gmaps controls moved too.

![bug_ie11](https://user-images.githubusercontent.com/16645947/27823575-dea8c6d2-60a9-11e7-9b50-0f18fd828628.png)

**Comment by zhenyanghua** [comment]
IE doesn't support the `Object.assign(target, ...sources)` syntax. It is going to be hard to support this. A poly fill will certainly work. Doe the polyfill fix the problem you have in the screenshot you provided? I don't have any device to get a windows license to test in IE 11 at the moment. If the polyfill works, could you make the PR?

**Comment by d-damien** [comment]
Sorry my message was not clearer. The polyfill only allows MeasureTool to work in IE11. Then you can see the bug :p

To test your websites with IE11, you can use the official (free) MS Windows testing ISO :

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

Choose "Microsoft Edge on Win 10

**Comment by zhenyanghua** [comment]
I added the polyfill in commit [cd2db4](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/cd2db4a7a605603047ea638b60da10eee860f65a). But with the latest version of Google Maps and this library, the sliding error cannot be reproduced in IE 11. Please reopen and provide instructions and screenshot if you can reproduce this error with the V0.0.12.
