### ISSUE TITLE
Zoom Control Issue

### ISSUE THREAD

**Issue by zaidrix** [zhenyanghua/MeasureTool-GoogleMaps-V3#13]
If the default "zoom control" is set to hidden (zoomControl: false) on map, it will show up right away after pressing the first point again to close the area (i.e. after the "Total Distance" message).

**Comment by zhenyanghua** [comment]
Without a reliable way to get the map current options, e.g. zoomControl in this case, there is no easy way to preserve the previous map state after overriding the map options during drawing process.

**Comment by zhenyanghua** [comment]
Current will use a select to determine the map zoomControl value:  `!!document.querySelector("button[aria-label='Zoom in']")`. This is the only way I can think of on top of my head. It works for this particular issue, but will have to check when there is a newer release of Google Maps API>

**Comment by zhenyanghua** [comment]
Fixed in commit [f69a65](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/f69a6534712c5856a231a446b4ea233c416b7e9a). Released in v0.0.15.
