### ISSUE TITLE
How to use it in vue ?

### ISSUE THREAD

**Issue by williambao** [zhenyanghua/MeasureTool-GoogleMaps-V3#14]
Hi,
It's can use it in vue project?
I have a project base on vue. and use [vue-google-maps](https://github.com/xkjyeah/vue-google-maps). i have no idea how to use it.

**Comment by zhenyanghua** [comment]
I don't have experience with Vue, but here is the general tip to use in other libraries -- make sure you reference the mentioned libraries in the document, and for es5 just use it like the example shows, for es6, use import from.
