### ISSUE TITLE
Context menu isn't visible when map is in full screen mode

### ISSUE THREAD

**Issue by vitosamson** [zhenyanghua/MeasureTool-GoogleMaps-V3#23]
This can be reproduced on the example page:

1. Remove the instructions div since it blocks the full screen button
2. Click the full screen button
3. Right-click on the map - context menu will not be visible
4. Exit full screen - context menu will be visible

I tried setting the `z-index` on `.measure-tool-context-menu` to a high value but that doesn't seem to solve the issue.

**Comment by zhenyanghua** [comment]
Fixed in commit [a6bba9](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/a6bba96d73ea7a8db14a7f30e7df828cb8c3f9ec). Released as v0.0.13.
