### ISSUE TITLE
draggable: true properties from map.data.setStyle not working

### ISSUE THREAD

**Issue by rynsp** [zhenyanghua/MeasureTool-GoogleMaps-V3#26]
if we use this library, draggable: true properties from map.data.setStyle not working.

**Comment by zhenyanghua** [comment]
It would be helpful if you could provide a working code that I can test against.

**Comment by zhenyanghua** [comment]
#22 is related to this issue.

**Comment by zhenyanghua** [comment]
Fixed in commit [5dacda](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/5dacdaf323d35434ced01584fecb759b506865bd). Released in v0.0.14.
