### ISSUE TITLE
Change color and background MeasureTool GoogleMaps

### ISSUE THREAD

**Issue by gerardew** [zhenyanghua/MeasureTool-GoogleMaps-V3#27]
Hi,

¿How can I change the color of the rectangle and the background?

Thanks.

**Comment by zhenyanghua** [comment]
You can't at this moment. You will have to tweak the css for the SVG
elements yourself.

Zhenyang Hua

**Comment by gerardew** [comment]
Can you tell me how to do this please?

Thanks.

**Comment by zhenyanghua** [comment]
Not in the scope of this project.

**Comment by zhenyanghua** [comment]
@gerardew Please use stackoverflow to ask CSS related questions.

**Comment by zhenyanghua** [comment]
v1.0.0 now allows invert the color of the tool

**Comment by jps5272** [comment]
Zhenyang I am developing an app and my developers are having a small issue building out the google measuring tool. I love this measuring tool you have built. I really need your help with a small consult on the app. Any help would be greatly appreciated. 
Thanks,
Patrick Scheil
washquoteapp@gmail.com
7045072021
