### ISSUE TITLE
MeasureTool disappears after zooming

### ISSUE THREAD

**Issue by rywall** [zhenyanghua/MeasureTool-GoogleMaps-V3#28]
* Go to http://zhenyanghua.github.io/google-maps/measure-tool/
* Add measurement line
* Zoom
* Measurement line is gone

Also, I can't add a measurement line after clearing a previous measurement line. I assume these are probably two manifestations of the same bug.

**Comment by rywall** [comment]
@zhenyanghua Do you have any advice on how to solve this issue?

**Comment by zhenyanghua** [comment]
Thanks for reporting this. I will get it fixed when I get a chance.

**Comment by rywall** [comment]
Thank you!

**Comment by zhenyanghua** [comment]
This is caused by an internal change on the Google `OverlayViewer` class, #29 is caused by the same change.

**Comment by zhenyanghua** [comment]
Fixed in [732c1da](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/732c1da4b4d4e2ba6ba9367d00bd66fcc1916245), updated npm release to v0.0.10
