### ISSUE TITLE
How to change the color and make it bold by default of the measurement text

### ISSUE THREAD

**Issue by nisharafic** [zhenyanghua/MeasureTool-GoogleMaps-V3#30]
Hi,

How to customize the distance text color and make it by default bold in all measurement. is there any settings available.?

thanks 
nishar

**Comment by zhenyanghua** [comment]
This tool is to mimic what the Google Maps does, changing the styles of the SVG element is not intended so there will not be settings that change to custom styles. However, there is nothing to stop you from changing the SVG element styles, you could inspect the elements and overwrite the styles. But if that causes the widget not to work properly, you will be responsible to handle it.
