### ISSUE TITLE
Add the number of points (count), and optionally a points array, to the measure result

### ISSUE THREAD

**Issue by oonk-mjm** [zhenyanghua/MeasureTool-GoogleMaps-V3#31]
Currently only the **length**, **lengthText**, **area** and **areaText** are added to the _measure-result_. It would be very useful if the _measure-result_ could be expanded with the _number of points_ (**pointsCount**) and optionally an array of all points (**points**).

**Comment by zhenyanghua** [comment]
Could you provide some use cases for this request?

**Comment by oonk-mjm** [comment]
I'm building a tool that will calculate the required materials for a fence (barrier used to keep animals). As an extra service, I would like to allow the user to use Google-maps to find and mark his property on the map. Each point/corner on the map indicates the need for an extra pole/post.

**Comment by zhenyanghua** [comment]
This is a good use case. In addition, instead of providing a collection of points, may be a collection of segments would be more useful, so each segment will contain two points and the segment length data. Something like below:

`MeasureResult`
```json
{
  "area": 1,
  "areaText": "1 sqkm",
  "length": 2000,
  "lengthText": "2km",
  "segments": [
    {
      "start_location": {
        "lat": 30.21,
        "lng": -82.11
      },
      "end_location": {
        "lat": 30.211,
        "lng": -82.101
      },
      "length": {
        "text": "500m",
        "value": 500
      }
    }
  ]
}
```

**Comment by oonk-mjm** [comment]
Adding the segments-collection to the result would be very useful (and might satisfy other use-cases as well).

**Comment by zhenyanghua** [comment]
Implemented `Segment` in the v0.1.0 release. changes in commit [083484](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/08348417c11d4c68c63448bd546ec5344e2b65e6).

**Comment by profileCaren** [comment]
I think it would still be useful to add a method to get the points in the measure tool, like

```js
let measureTool = new MeasureTool(..);

// user draw ...

measureTool.getPoints(); // return [{lat: 10, lng: 10}, {lat: 20, lng : 20} ...];
```

There are 3 reasons for this:
1. Using this method I don't have to get the `MeasureResult` only when user trigger events (`measure_start`, `measure_end`, `measure_change`).

2. Even though I've got the `MeasureResult`,  using `MeasureResult` I have to parse the `start_location` and `end_location` of every `segments` to get the points.  And If I simply push them (`start_location` and `end_location`) into an array, I would have to do the deduplication work (as every two adjacent segments will have at least one same point ), which is kind of annoying.

3. The new feature in v0.3.0 allow user to pass an array of points to `start()`, like
```js
`measureTool.start([{lat: 47.94796, lng: -116.70797}, {lat: 47.95028, lng: -116.69907}])`
```

**Comment by zhenyanghua** [comment]
Even though you could achieve this with existing API, by mapping the segments, I do see it comes handy. I plan to add getters for segments and points in the next release (v0.4.0).
