### ISSUE TITLE
measure_end -> listener -> function doesn't receive the full result (segments omitted)

### ISSUE THREAD

**Issue by oonk-mjm** [zhenyanghua/MeasureTool-GoogleMaps-V3#32]
measure_change: segments are in the result;
measure_end: segments are not in the result.

**Comment by oonk-mjm** [comment]
The segments are not part of the result.

**Comment by zhenyanghua** [comment]
Fixed in v0.1.1. See commit [d7316c](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/d7316ce4af1a6a23440ea7f31a1c37937cbf250c).
