### ISSUE TITLE
Disable and Enable rigth click menu

### ISSUE THREAD

**Issue by wellitongervickas** [zhenyanghua/MeasureTool-GoogleMaps-V3#33]
Hi, im used your tool in my project, but i have a conflict in right click event (show a menu). I have an event in the map and create my custom menu. My suggest is in your tool options, enable and disable that event.

Ex:  measureTool = new MeasureTool(mapRef, {
      tooltip: false,
      dropdownMenu: false
    });

And thankyou of this project.

**Comment by zhenyanghua** [comment]
Please turn to the reference for help before raising a question. Refer to the section - [Bind to Your Own UI](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3#bind-to-your-own-ui).
