### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by tghamm** [zhenyanghua/MeasureTool-GoogleMaps-V3#34]
Hi there, it seems something is wrong with the demo.  It worked last week, but now right-clicking appears to do nothing.

Thanks!

**Comment by tghamm** [comment]
As a follow-up: It seems 0.1.2 has caused some kind of regression, right-click does nothing. 0.1.1 seems to work, except for the bug that 0.1.2 was designed to resolve (we're having the same issue).

**Comment by zhenyanghua** [comment]
This was caused by a bug introduced from 0.1.2.

**Comment by zhenyanghua** [comment]
Fixed in v0.1.3. Commit [e8ea35](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/e8ea35b29b7e7dd6ad2293aac85fdcb5523eac3d).

**Comment by tghamm** [comment]
Great, 0.1.4 seems to address all the issues.

Thanks!
