### ISSUE TITLE
Double click is required after measureTool end 

### ISSUE THREAD

**Issue by wellitongervickas** [zhenyanghua/MeasureTool-GoogleMaps-V3#36]
I need dbl click to start again after disabled measure tool.

`<button onclick="measureTool.start()">start</button>`
`<button onclick="measureTool.end()">end</button>`

- Start drawing
- Drawing in map
- Disable tool
- Start drawing again and here is the bug...

How i fix this?

**Comment by zhenyanghua** [comment]
Could you provide a live example to reproduce your bug using this [template](https://jsbin.com/jedecumuna/1/edit?html,output)? Thanks.

**Comment by zhenyanghua** [comment]
Have not heard anything from you. Close it for now. Feel free to reopen it with a concrete example.
