### ISSUE TITLE
Nautical Miles

### ISSUE THREAD

**Issue by steveneal** [zhenyanghua/MeasureTool-GoogleMaps-V3#39]
Hi.

I've added a NAUTICAL type locally, that extends the IMPERIAL and METRIC types, so that nautical miles can be used measurement units.

I need this to be able to use your tool. Can I create a branch to push this to for you to pull? Or is it something you could add quickly. It's just a few lines of code.

Thanks, Steve.

**Comment by zhenyanghua** [comment]
Excellent! You can create a pull-request and after testing it I will merge your pull-request to the master branch.

**Comment by steveneal** [comment]
I can't create a branch to push my changes to in order to set up a pull
request.

Can you set me up as a collaborator?

**Comment by zhenyanghua** [comment]
you should follow the recommended GitHub collaboration flow for the pull request. Fork from mine and make the changes on yours and submit the PR to merge into mine. and I will take it from there. Thanks!

**Comment by steveneal** [comment]
Done apologies for the confusion :)

**Comment by zhenyanghua** [comment]
Merged in [PR #40 ](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/pull/40)
