### ISSUE TITLE
Issue with duplication of line after zoom

### ISSUE THREAD

**Issue by Ivan-McA** [zhenyanghua/MeasureTool-GoogleMaps-V3#41]
I'm seeing an issue where if you draw a line and then zoom in and out a bit (using the zoom buttons- mouse wheel doesn't seem to do it) the line can get duplicated. It takes quite a bit of zooming in and out to do this, but if you rapidly zoom in and out it will duplicate.

I see this in Chrome  66.0.3359.170 (Official Build) (64-bit) on Windows. Also in Opera 52.0.2871.99 and Firefox 59.0.2.

![measuretool_bug](https://user-images.githubusercontent.com/34710760/39997620-bf0572de-57ad-11e8-9741-4999702e2dfb.png)

This seems related, but was fixed in a newer version of Chrome, while I am still seeing this issue in Chrome 66.

https://stackoverflow.com/questions/45406218/google-maps-api-issue-broken-duplication-of-shapes-after-zooming

**Comment by zhenyanghua** [comment]
I recently tested this again, and could not reproduce this problem with the latest Chrome and FireFox. The problem might be gone. While there is no code changes address this issue from this library, it might be Google Maps JavaScript API update that removes this bug. Will keep this issue open for a while until it seems stable.

**Comment by becerriljc** [comment]
i have the same bug in my application, i try this in your demo and this the result:

![demo](https://user-images.githubusercontent.com/24251698/51217425-b1c05b00-18ed-11e9-96a6-1d7e053ed40e.png)

**Comment by ronakshethia** [comment]
hi am seeing the same issue there is duplication of polylines when zoom in and zoom out

**Comment by mrbraca15** [comment]
same problem with chrome v75.0.3770.142 and firefox 68.0.1, its easy to reproduce, you need to do scroll down and scroll up on map very faster for some seconds.
![image](https://user-images.githubusercontent.com/11879228/61660086-b431b200-ac8e-11e9-8466-6d4ffe533cfb.png)

**Comment by zhenyanghua** [comment]
It might be caused by the redraw when the projection spans over multiple worlds.

**Comment by zhenyanghua** [comment]
This release addresses this problem. https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/releases/tag/v0.4.1

**Comment by mrbraca15** [comment]
the releases works but throw new error when try to clean the measure on the map

![imagen](https://user-images.githubusercontent.com/11879228/62392710-c1239080-b52d-11e9-9214-51c0bf948d34.png)

**Comment by zhenyanghua** [comment]
0.4.2 solved the problem.
