### ISSUE TITLE
[Question] How can I fill the polygon shapes with a color? 

### ISSUE THREAD

**Issue by RainierMallol** [zhenyanghua/MeasureTool-GoogleMaps-V3#49]
When a polygon is drawn, I'd like to have its content of a certain color, instead of transparent. 

Is this something doable?

**Comment by zhenyanghua** [comment]
Not directly. But with the [events](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/blob/master/docs/REFERENCE.md#measureevent-object-specification), you could do use other tools or Google Maps API to draw your polygon.
