### ISSUE TITLE
Integration problem : lib/index.js file does not exist

### ISSUE THREAD

**Issue by d-damien** [zhenyanghua/MeasureTool-GoogleMaps-V3#5]
As the title says. `package.json`'s `main` parameter value is a file name that does not exist, which can break integration in frameworks or build tools (it does in Angular + Webpack). Could you change the value or add a symlink from `lib/MeasureTool.min.js` ?

Thanks for your cool plugin.

**Comment by zhenyanghua** [comment]
Thanks for the advice - fixed in [v0.0.7](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/blob/master/package.json#L3-L5). Published to npm. Please let me know if it works for your packaging system, and close it if it resolves your issue.

**Comment by d-damien** [comment]
It works, thank you :world_map:
