### ISSUE TITLE
[feature] connect the first and the last point

### ISSUE THREAD

**Issue by profileCaren** [zhenyanghua/MeasureTool-GoogleMaps-V3#51]
As the title suggests, it would be perfect if the first and the last point are connected.

**Comment by zhenyanghua** [comment]
This will not be implemented at this moment. This tool is to give similar experience to the users who enjoys using the measure tool from Google Maps so that they could also use it with the Google Maps API.

**Comment by profileCaren** [comment]
@zhenyanghua Okay.
