### ISSUE TITLE
the webAPP is slow after installing the package (caused by CSS BLOB files)

### ISSUE THREAD

**Issue by davidescurria** [zhenyanghua/MeasureTool-GoogleMaps-V3#53]
I noticed that after installing the package the webAPP slows down at startup.
Analyzing the behavior through the tools provided by the browser I noticed that 3 BLOB files are created. They are 3 CSS files (adding up the CSS classes are about 10). The problem is that it takes 5 to 7 seconds to process these files. Is it possible to disable the creation of these 3 BLOB files ?

**Comment by zhenyanghua** [comment]
From webpack site:
> Source maps and assets referenced with url: when style loader is used with { options: { sourceMap: true } } option, the CSS modules will be generated as Blobs, so relative paths don't work (they would be relative to chrome:blob or chrome:devtools). In order for assets to maintain correct paths setting output.publicPath property of webpack configuration must be set, so that absolute paths are generated. Alternatively you can enable the convertToAbsoluteUrls option mentioned above.

If we change the sourcemap option to `false`, it may not generate the blob. try it out.

**Comment by davidescurria** [comment]
I'm developing my project with Angular 4. I tried to add `sourceMap: false` but it is generated anyway

**Comment by zhenyanghua** [comment]
You need to rebuild this project with the webpack css/sass loader option: `sourceMap: false`, and then build it. You don't need to set the sourceMap to false if you don't open the dev tool in your browser in production, it effectively won't download the sourceMap and blobs. But if you choose to keep your sourcemap a secret in production, you can just build this project with sourceMap to false.
