### ISSUE TITLE
Prevent new points change the end of route

### ISSUE THREAD

**Issue by Rumpelstinsk** [zhenyanghua/MeasureTool-GoogleMaps-V3#54]
When you pass in an array of points when starting measurement, it would be great to have an option to prevent changing the last point of the route.

I initializate the component with 2 points, start and end of route. It would be great if the user could add new points by clicking on the segments, to adjust to route to streets or whatever, but prevent the map's click to mantain the end of route.

**Comment by zhenyanghua** [comment]
Not sure what you mean. Isn't it already supported?

**Comment by Rumpelstinsk** [comment]
Maybe i'm wrong but, I don't think so. 

For example: if I initialice the tool with 2 points:  Spain-Germany
a) The user can click on the map, making a new route: Spain-Germany-France
b) The user can click on the drawed line to add a new "stoppoint", modifyng the route: Spain-France-Germany

What I want to prevent is option a), but making option b) still available.

**Comment by zhenyanghua** [comment]
This is the way this tool was designed. Its goal is to mimic what current Google Maps does. Sorry.
