### ISSUE TITLE
Gets slow in responsive mode

### ISSUE THREAD

**Issue by rathodrupesha** [zhenyanghua/MeasureTool-GoogleMaps-V3#56]
Hello,
we implemented this plugin in one of my projects.
it works properly in normal mode in the browser.
but in the responsive mode, it's getting slow
so how to improve performance in responsive mode?

**Comment by zhenyanghua** [comment]
Could you give example of *responsive mode*. I am not sure I understand your use case. Thanks.

**Comment by zhenyanghua** [comment]
Not active issue, closed.
