### ISSUE TITLE
When is redrawOverlay necessary?

### ISSUE THREAD

**Issue by WillWhiteneck** [zhenyanghua/MeasureTool-GoogleMaps-V3#57]
redrawOverlay gets called whenever the map is zoomed, it requires a lot of computation and I can't tell whether or not it's necessary. I tried removing it and everything seemed to work the same, with a big performance boost when zooming. Is there some corner case I'm unaware of where redrawOverlay is needed?

https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/blob/42ce0dc7f8f25002b3853287beabfe222cf3a5a4/src/index.js#L303-L307

**Comment by zhenyanghua** [comment]
This is something that I don't know for sure. Because this tool is dealing directly with an blackboxed API, I cannot predict the behavior from google maps API when it internally decides to not render when map scales, with this private method, it at least follows the recommendation from the google maps reference so nothing broken has been reported yet.

**Comment by WillWhiteneck** [comment]
I'm new to the google maps API, but I can't find anything that says it's necessary to reinitialize the svg overlayView when zooming. I've been looking for about an hour, either I'm not seeing it or they have recently changed it.

https://developers.google.com/maps/documentation/javascript/reference/3.36/overlay-view

**Comment by zhenyanghua** [comment]
I couldn't find it anymore either. I am not sure how stable it is without it, as in the past it was an issue sometimes the `draw()` from google maps API wasn't stable to resize the overlay pane, that was the reason this was introduced.

**Comment by zhenyanghua** [comment]
It might caused a side effect when zooming and scrolling when map projection spans across multiple worlds. #41.

**Comment by zhenyanghua** [comment]
I will remove the redraw event from the new release.

**Comment by zhenyanghua** [comment]
https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/releases/tag/v0.4.1
