### ISSUE TITLE
Need Area Of Total

### ISSUE THREAD

**Issue by cgvaghela** [zhenyanghua/MeasureTool-GoogleMaps-V3#58]
Hello,

I retrieved Polygon Point from OSM (Nominatim). It's Works fine to draw Polygon and Rectangle.
I Need Area of Polygon & Rectangle both. (Distance & Measure Both)
I am using google map for drawing.

Thank You in Advance

**Comment by zhenyanghua** [comment]
This is specific features that is not implemented by Google, so I won't implement it in this tool at this point.
