### ISSUE TITLE
Need an option to move the points through code 

### ISSUE THREAD

**Issue by jayapalchandran** [zhenyanghua/MeasureTool-GoogleMaps-V3#59]
Hi,

I had been using this tool to measure area.
I thought that if there could be an option to move the selection through code other than mouse then that would be of much help as it would allow the user to move the points precisely.

Thank you

**Comment by zhenyanghua** [comment]
Sorry, this isn't the intent of this library. If you want to mimic what similar to programmatically change the points, you will need to restart the measurement with a list of points, which effectively does the same thing: https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/blob/master/docs/GUIDE.md#start-measurement-with-initial-points
