### ISSUE TITLE
On end

### ISSUE THREAD

**Issue by Philwn** [zhenyanghua/MeasureTool-GoogleMaps-V3#6]
Is there a way of listening for the end method to start another event?

Basically when the area is calculated I need it to insert that numerical value in a text box.

**Comment by zhenyanghua** [comment]
No, it doesn't at the moment. I will add it in the next milestone. For now you will have to run your methods after every single `end()` is called. Stay tuned.

**Comment by zhenyanghua** [comment]
Added this feature in v0.0.8. see [115e03d](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/115e03d2c32f454f5a700584cf978aa72bbedaca).
