### ISSUE TITLE
Android - Chrome and Firefox || Measurement Tool not working

### ISSUE THREAD

**Issue by yogeshpaisode** [zhenyanghua/MeasureTool-GoogleMaps-V3#60]
Hello Team,

Measurement Tools not working on Android - Chrome and Firefox.

Please open below Fiddle in Android Chrome or Firefox.

https://jsfiddle.net/yogesh_paisode/93qesuc5/5/

Thanks!

**Comment by zhenyanghua** [comment]
Unfortunately this library is not supported in Mobile devices.

**Comment by zhenyanghua** [comment]
https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/issues/43#issuecomment-420635558

**Comment by yogeshpaisode** [comment]
Is there any solution to this or do you suggest any other library on this?

**Comment by zhenyanghua** [comment]
Sorry, there won't be any solution within the scope of this library.

**Comment by zhenyanghua** [comment]
It is now implemented in v1.0.0
