### ISSUE TITLE
Measurement Tools not supporting language other than English.

### ISSUE THREAD

**Issue by yogeshpaisode** [zhenyanghua/MeasureTool-GoogleMaps-V3#61]
Hello Team,

Measurement Tools not supporting language other than English.

Change your browser language to other than English. Open below JS Fiddle and observe that measurements tool not supporting the language other than English.

https://jsfiddle.net/yogesh_paisode/93qesuc5/5/

Thanks!

**Comment by zhenyanghua** [comment]
#48 reflects this limitation. It is planned, but don't have a timeline yet. I am closing it and please use #48 for discussion.

**Comment by zhenyanghua** [comment]
It is now implemented in v1.0.0
