### ISSUE TITLE
Display degrees of line next to distance

### ISSUE THREAD

**Issue by vchrizz** [zhenyanghua/MeasureTool-GoogleMaps-V3#62]
Would it be possible to add the degrees next to the distance of a measured line?

An example I have seen on another map:
![map-distance-with-degrees](https://user-images.githubusercontent.com/5678480/73211432-8309d100-414c-11ea-8d14-b0943fc9ba96.png)

**Comment by zhenyanghua** [comment]
I can see there might be some use case for it, but not as strong as the basic distance and area measurement. There is no plan to support it at this moment. But I know it is definitely feasible with the current code base. I encourage a PR for it if you are going to implement. The PR should also make it configurable so users could opt-out.
