### ISSUE TITLE
Question: How can I change the font-color and font-size properties on the labels?

### ISSUE THREAD

**Issue by oscarlaf03** [zhenyanghua/MeasureTool-GoogleMaps-V3#64]
Hello, sorry for the trouble I was looking into the developer guide but couldn't find information regarding how the change the labels with the measurements' information to white color since I am using them on top of  a satellite view of GoogleMaps and the default black color is very unreadable.

any ideas?

![image](https://user-images.githubusercontent.com/29902457/73549839-2ba48300-4422-11ea-924b-66c085fdd304.png)

**Comment by zhenyanghua** [comment]
You could inspect the elements and override with CSS.  You may find some info by reading the source code:

https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/blob/master/src/index.scss

**Comment by oscarlaf03** [comment]
Thank you very much!!! this helps a great deal!

All the best

OO
