### ISSUE TITLE
Trigger Context Menu Via Button

### ISSUE THREAD

**Issue by asyadiqin** [zhenyanghua/MeasureTool-GoogleMaps-V3#65]
First of all, this is an awesome tool, so kudos to the developer and contributors.

I am not sure if this is the right place to ask question but is there a way to trigger the context menu via a button with a possible customizable point on the map or just default to the default map centre? I think this would address some issues with mobile users having problem to right-click on the screen.
If it's possible, would be great if you could post a sample code to do this.

Thanks and looking forward to a prompt response.

Regards,
Allie Syadiqin

**Comment by zhenyanghua** [comment]
Unfortunately it is not supported in Mobile Device for this library.

**Comment by zhenyanghua** [comment]
https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/issues/43#issuecomment-420635558

**Comment by asyadiqin** [comment]
OK. What I am asking is whether there is a way to trigger the context menu
via a button... so not really looking to for use in mobile device. Thanks

**Comment by zhenyanghua** [comment]
There is no direct way. But you could export the ContextMenu class and use it with the API if you like:
https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/blob/master/src/context-menu.js
