### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by viktorvi** [zhenyanghua/MeasureTool-GoogleMaps-V3#7]
Multilanguage support or possibilities to translate expressions to custom language would be great! 

I am using it in a project which language is German or French.

**Comment by zhenyanghua** [comment]
Will add support for internationalization and localization in the next release, stay tuned.

**Comment by okainov** [comment]
+1

**Comment by zhenyanghua** [comment]
This will be part of  #48 as a new feature in v1.0.0 next year.

**Comment by marcosddourado** [comment]
+1

**Comment by zhenyanghua** [comment]
Implemented in v1.0.0
