### ISSUE TITLE
Zoom control

### ISSUE THREAD

**Issue by viktorvi** [zhenyanghua/MeasureTool-GoogleMaps-V3#8]
When I drag the "white circle" then the +- zoom control of the map disappear. You can reproduce this problem with your demo.

http://zhenyanghua.github.io/google-maps/measure-tool/

![image](https://user-images.githubusercontent.com/10329678/26972564-a380219a-4d12-11e7-890d-2029c1159e08.png)

**Comment by zhenyanghua** [comment]
This is a current limitation of this library. While you are dragging a point, if you zoom the map, the SVG canvas will be redrawn which will remove current SVG being dragged from the canvas, and the event will also disappear. So zooms are disabled to prevent it from happening.

**Comment by zhenyanghua** [comment]
This is a current limitation of this library. While you are dragging a point, if you zoom the map, the SVG canvas will be redrawn which will remove current SVG being dragged from the canvas, and the event will also disappear. So zooms are disabled to prevent it from happening.
