### ISSUE TITLE
measure_end Listener

### ISSUE THREAD

**Issue by Philwn** [zhenyanghua/MeasureTool-GoogleMaps-V3#9]
Im not sure if this is an issue or the intended use.

The measure_end listener is only trigged when you clear measurements. I expected it to trigger when you complete a drawing area.

Currently when you finish drawing an area on the map the calculated area is written on the map. At this same point I need to trigger it to populate a text input with the calculated area?

is this an issue? if so is it possible to add another listener? there is obviously a trigger which writes the calculated area on the map.

**Comment by zhenyanghua** [comment]
This is a good point. I will soon add another event called `measure_click` to provide the current `MeasureResult` to the subscribers. However, when ending a measurement, the measurement overlay being cleared is the intention.

**Comment by zhenyanghua** [comment]
Added `measure_change` event for this need. [v0.0.9](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/tree/v0.0.9)
