### ISSUE TITLE
Using CDN does not work at times

### ISSUE THREAD

**Issue by Ares1605** [zhenyanghua/MeasureTool-GoogleMaps-V3#95]
using the 'https://unpkg.com/measuretool-googlemaps-v3' CDN timeouts after a minute some of the time. One minute it will be working fine, the next minute it is taking forever to load the content. Is there a reason for this? Will using an ESM with npm solve the issue?

**Comment by adjenks** [comment]
The owner of the library is not responsible for the reliability of thr CDN. If you need better reliability you need to build the package yourself and host it on your own domain.
